name: Run PyTests
on: [push]

jobs:
  run:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Test with pytest
        run: pytest -vv
